//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tpWcfCalculPrixTvaClient.Calcul {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TVAService.ETVA", Namespace="http://schemas.datacontract.org/2004/07/tpWcfCalculPrixTvaServiceTVA")]
    public enum TVAServiceETVA : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 2000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Restau = 1000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Epicerie = 550,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medoc = 210,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Calcul.ICalculeService")]
    public interface ICalculeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculeService/Calcule", ReplyAction="http://tempuri.org/ICalculeService/CalculeResponse")]
        double Calcule(int quantite, string article, double prix, tpWcfCalculPrixTvaClient.Calcul.TVAServiceETVA categorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculeService/Calcule", ReplyAction="http://tempuri.org/ICalculeService/CalculeResponse")]
        System.Threading.Tasks.Task<double> CalculeAsync(int quantite, string article, double prix, tpWcfCalculPrixTvaClient.Calcul.TVAServiceETVA categorie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculeServiceChannel : tpWcfCalculPrixTvaClient.Calcul.ICalculeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculeServiceClient : System.ServiceModel.ClientBase<tpWcfCalculPrixTvaClient.Calcul.ICalculeService>, tpWcfCalculPrixTvaClient.Calcul.ICalculeService {
        
        public CalculeServiceClient() {
        }
        
        public CalculeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Calcule(int quantite, string article, double prix, tpWcfCalculPrixTvaClient.Calcul.TVAServiceETVA categorie) {
            return base.Channel.Calcule(quantite, article, prix, categorie);
        }
        
        public System.Threading.Tasks.Task<double> CalculeAsync(int quantite, string article, double prix, tpWcfCalculPrixTvaClient.Calcul.TVAServiceETVA categorie) {
            return base.Channel.CalculeAsync(quantite, article, prix, categorie);
        }
    }
}
