//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleItemClient.NSItem {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NSItem.IItemService")]
    public interface IItemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetItemByparameter", ReplyAction="http://tempuri.org/IItemService/GetItemByparameterResponse")]
        Items.Item GetItemByparameter(double prix, string marque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetItemByparameter", ReplyAction="http://tempuri.org/IItemService/GetItemByparameterResponse")]
        System.Threading.Tasks.Task<Items.Item> GetItemByparameterAsync(double prix, string marque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/UpdateItem", ReplyAction="http://tempuri.org/IItemService/UpdateItemResponse")]
        Items.Item UpdateItem(Items.Item value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/UpdateItem", ReplyAction="http://tempuri.org/IItemService/UpdateItemResponse")]
        System.Threading.Tasks.Task<Items.Item> UpdateItemAsync(Items.Item value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetListItem", ReplyAction="http://tempuri.org/IItemService/GetListItemResponse")]
        System.Collections.Generic.List<Items.Item> GetListItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetListItem", ReplyAction="http://tempuri.org/IItemService/GetListItemResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Items.Item>> GetListItemAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IItemServiceChannel : ConsoleItemClient.NSItem.IItemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemServiceClient : System.ServiceModel.ClientBase<ConsoleItemClient.NSItem.IItemService>, ConsoleItemClient.NSItem.IItemService {
        
        public ItemServiceClient() {
        }
        
        public ItemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Items.Item GetItemByparameter(double prix, string marque) {
            return base.Channel.GetItemByparameter(prix, marque);
        }
        
        public System.Threading.Tasks.Task<Items.Item> GetItemByparameterAsync(double prix, string marque) {
            return base.Channel.GetItemByparameterAsync(prix, marque);
        }
        
        public Items.Item UpdateItem(Items.Item value) {
            return base.Channel.UpdateItem(value);
        }
        
        public System.Threading.Tasks.Task<Items.Item> UpdateItemAsync(Items.Item value) {
            return base.Channel.UpdateItemAsync(value);
        }
        
        public System.Collections.Generic.List<Items.Item> GetListItem() {
            return base.Channel.GetListItem();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Items.Item>> GetListItemAsync() {
            return base.Channel.GetListItemAsync();
        }
    }
}
