//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tpWcfCalculPrixTvaService.CalculeTVA {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TVAService.ETVA", Namespace="http://schemas.datacontract.org/2004/07/tpWcfCalculPrixTvaServiceTVA")]
    public enum TVAServiceETVA : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 2000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Restau = 1000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Epicerie = 550,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medoc = 210,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculeTVA.ITVAService")]
    public interface ITVAService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITVAService/CalculTVA", ReplyAction="http://tempuri.org/ITVAService/CalculTVAResponse")]
        double CalculTVA(double prixTTC, tpWcfCalculPrixTvaService.CalculeTVA.TVAServiceETVA cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITVAService/CalculTVA", ReplyAction="http://tempuri.org/ITVAService/CalculTVAResponse")]
        System.Threading.Tasks.Task<double> CalculTVAAsync(double prixTTC, tpWcfCalculPrixTvaService.CalculeTVA.TVAServiceETVA cat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITVAServiceChannel : tpWcfCalculPrixTvaService.CalculeTVA.ITVAService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TVAServiceClient : System.ServiceModel.ClientBase<tpWcfCalculPrixTvaService.CalculeTVA.ITVAService>, tpWcfCalculPrixTvaService.CalculeTVA.ITVAService {
        
        public TVAServiceClient() {
        }
        
        public TVAServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TVAServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TVAServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TVAServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalculTVA(double prixTTC, tpWcfCalculPrixTvaService.CalculeTVA.TVAServiceETVA cat) {
            return base.Channel.CalculTVA(prixTTC, cat);
        }
        
        public System.Threading.Tasks.Task<double> CalculTVAAsync(double prixTTC, tpWcfCalculPrixTvaService.CalculeTVA.TVAServiceETVA cat) {
            return base.Channel.CalculTVAAsync(prixTTC, cat);
        }
    }
}
