//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppEmploye.NSEmploye {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employe", Namespace="http://schemas.datacontract.org/2004/07/Employes")]
    [System.SerializableAttribute()]
    public partial class Employe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NSEmploye.ISrvEmploye")]
    public interface ISrvEmploye {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEmploye/GetEmploye", ReplyAction="http://tempuri.org/ISrvEmploye/GetEmployeResponse")]
        ConsoleAppEmploye.NSEmploye.Employe GetEmploye();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvEmploye/GetEmploye", ReplyAction="http://tempuri.org/ISrvEmploye/GetEmployeResponse")]
        System.Threading.Tasks.Task<ConsoleAppEmploye.NSEmploye.Employe> GetEmployeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISrvEmployeChannel : ConsoleAppEmploye.NSEmploye.ISrvEmploye, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SrvEmployeClient : System.ServiceModel.ClientBase<ConsoleAppEmploye.NSEmploye.ISrvEmploye>, ConsoleAppEmploye.NSEmploye.ISrvEmploye {
        
        public SrvEmployeClient() {
        }
        
        public SrvEmployeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SrvEmployeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvEmployeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvEmployeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleAppEmploye.NSEmploye.Employe GetEmploye() {
            return base.Channel.GetEmploye();
        }
        
        public System.Threading.Tasks.Task<ConsoleAppEmploye.NSEmploye.Employe> GetEmployeAsync() {
            return base.Channel.GetEmployeAsync();
        }
    }
}
