//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tpWcfAccesBaseConsole.NS1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/tpDaoArticles")]
    [System.SerializableAttribute()]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NS1.IAccesBaseService")]
    public interface IAccesBaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesBaseService/SelectById", ReplyAction="http://tempuri.org/IAccesBaseService/SelectByIdResponse")]
        tpWcfAccesBaseConsole.NS1.Article SelectById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesBaseService/SelectById", ReplyAction="http://tempuri.org/IAccesBaseService/SelectByIdResponse")]
        System.Threading.Tasks.Task<tpWcfAccesBaseConsole.NS1.Article> SelectByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesBaseService/SelectAll", ReplyAction="http://tempuri.org/IAccesBaseService/SelectAllResponse")]
        tpWcfAccesBaseConsole.NS1.Article[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesBaseService/SelectAll", ReplyAction="http://tempuri.org/IAccesBaseService/SelectAllResponse")]
        System.Threading.Tasks.Task<tpWcfAccesBaseConsole.NS1.Article[]> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesBaseService/Insert", ReplyAction="http://tempuri.org/IAccesBaseService/InsertResponse")]
        void Insert(tpWcfAccesBaseConsole.NS1.Article article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesBaseService/Insert", ReplyAction="http://tempuri.org/IAccesBaseService/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(tpWcfAccesBaseConsole.NS1.Article article);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccesBaseServiceChannel : tpWcfAccesBaseConsole.NS1.IAccesBaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccesBaseServiceClient : System.ServiceModel.ClientBase<tpWcfAccesBaseConsole.NS1.IAccesBaseService>, tpWcfAccesBaseConsole.NS1.IAccesBaseService {
        
        public AccesBaseServiceClient() {
        }
        
        public AccesBaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccesBaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccesBaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccesBaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public tpWcfAccesBaseConsole.NS1.Article SelectById(int id) {
            return base.Channel.SelectById(id);
        }
        
        public System.Threading.Tasks.Task<tpWcfAccesBaseConsole.NS1.Article> SelectByIdAsync(int id) {
            return base.Channel.SelectByIdAsync(id);
        }
        
        public tpWcfAccesBaseConsole.NS1.Article[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<tpWcfAccesBaseConsole.NS1.Article[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public void Insert(tpWcfAccesBaseConsole.NS1.Article article) {
            base.Channel.Insert(article);
        }
        
        public System.Threading.Tasks.Task InsertAsync(tpWcfAccesBaseConsole.NS1.Article article) {
            return base.Channel.InsertAsync(article);
        }
    }
}
