//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceHello.OperationUpper {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperationUpper.IServiceUpper")]
    public interface IServiceUpper {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUpper/GetUpper", ReplyAction="http://tempuri.org/IServiceUpper/GetUpperResponse")]
        string GetUpper(string v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUpper/GetUpper", ReplyAction="http://tempuri.org/IServiceUpper/GetUpperResponse")]
        System.Threading.Tasks.Task<string> GetUpperAsync(string v);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUpperChannel : WcfServiceHello.OperationUpper.IServiceUpper, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUpperClient : System.ServiceModel.ClientBase<WcfServiceHello.OperationUpper.IServiceUpper>, WcfServiceHello.OperationUpper.IServiceUpper {
        
        public ServiceUpperClient() {
        }
        
        public ServiceUpperClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUpperClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUpperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUpperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUpper(string v) {
            return base.Channel.GetUpper(v);
        }
        
        public System.Threading.Tasks.Task<string> GetUpperAsync(string v) {
            return base.Channel.GetUpperAsync(v);
        }
    }
}
