//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClientPersonne.NSServicePersonne {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personne", Namespace="http://schemas.datacontract.org/2004/07/WcfServicePersonne.Model")]
    [System.SerializableAttribute()]
    public partial class Personne : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NSServicePersonne.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPersonne", ReplyAction="http://tempuri.org/IService1/GetPersonneResponse")]
        WCFClientPersonne.NSServicePersonne.Personne GetPersonne();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPersonne", ReplyAction="http://tempuri.org/IService1/GetPersonneResponse")]
        System.Threading.Tasks.Task<WCFClientPersonne.NSServicePersonne.Personne> GetPersonneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        WCFClientPersonne.NSServicePersonne.Personne Update(WCFClientPersonne.NSServicePersonne.Personne p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        System.Threading.Tasks.Task<WCFClientPersonne.NSServicePersonne.Personne> UpdateAsync(WCFClientPersonne.NSServicePersonne.Personne p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPersonneParam", ReplyAction="http://tempuri.org/IService1/GetPersonneParamResponse")]
        WCFClientPersonne.NSServicePersonne.Personne GetPersonneParam(string nom, string prenom, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPersonneParam", ReplyAction="http://tempuri.org/IService1/GetPersonneParamResponse")]
        System.Threading.Tasks.Task<WCFClientPersonne.NSServicePersonne.Personne> GetPersonneParamAsync(string nom, string prenom, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPersonne", ReplyAction="http://tempuri.org/IService1/GetListPersonneResponse")]
        System.Collections.Generic.List<WCFClientPersonne.NSServicePersonne.Personne> GetListPersonne();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPersonne", ReplyAction="http://tempuri.org/IService1/GetListPersonneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WCFClientPersonne.NSServicePersonne.Personne>> GetListPersonneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCFClientPersonne.NSServicePersonne.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCFClientPersonne.NSServicePersonne.IService1>, WCFClientPersonne.NSServicePersonne.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WCFClientPersonne.NSServicePersonne.Personne GetPersonne() {
            return base.Channel.GetPersonne();
        }
        
        public System.Threading.Tasks.Task<WCFClientPersonne.NSServicePersonne.Personne> GetPersonneAsync() {
            return base.Channel.GetPersonneAsync();
        }
        
        public WCFClientPersonne.NSServicePersonne.Personne Update(WCFClientPersonne.NSServicePersonne.Personne p) {
            return base.Channel.Update(p);
        }
        
        public System.Threading.Tasks.Task<WCFClientPersonne.NSServicePersonne.Personne> UpdateAsync(WCFClientPersonne.NSServicePersonne.Personne p) {
            return base.Channel.UpdateAsync(p);
        }
        
        public WCFClientPersonne.NSServicePersonne.Personne GetPersonneParam(string nom, string prenom, int age) {
            return base.Channel.GetPersonneParam(nom, prenom, age);
        }
        
        public System.Threading.Tasks.Task<WCFClientPersonne.NSServicePersonne.Personne> GetPersonneParamAsync(string nom, string prenom, int age) {
            return base.Channel.GetPersonneParamAsync(nom, prenom, age);
        }
        
        public System.Collections.Generic.List<WCFClientPersonne.NSServicePersonne.Personne> GetListPersonne() {
            return base.Channel.GetListPersonne();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WCFClientPersonne.NSServicePersonne.Personne>> GetListPersonneAsync() {
            return base.Channel.GetListPersonneAsync();
        }
    }
}
