//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWCFFull.NS2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NS2.IServiceJacky")]
    public interface IServiceJacky {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJacky/GetCoucou", ReplyAction="http://tempuri.org/IServiceJacky/GetCoucouResponse")]
        string GetCoucou(string v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJacky/GetCoucou", ReplyAction="http://tempuri.org/IServiceJacky/GetCoucouResponse")]
        System.Threading.Tasks.Task<string> GetCoucouAsync(string v);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceJackyChannel : ClientWCFFull.NS2.IServiceJacky, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceJackyClient : System.ServiceModel.ClientBase<ClientWCFFull.NS2.IServiceJacky>, ClientWCFFull.NS2.IServiceJacky {
        
        public ServiceJackyClient() {
        }
        
        public ServiceJackyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceJackyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJackyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJackyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCoucou(string v) {
            return base.Channel.GetCoucou(v);
        }
        
        public System.Threading.Tasks.Task<string> GetCoucouAsync(string v) {
            return base.Channel.GetCoucouAsync(v);
        }
    }
}
